### PR TITLE
movie details data

### PR DESCRIPTION
**Pull request by afrimzenuni**
when loaded, data defaults to "The Dark Knight", if you make a search it will load data for that search

### CODE REVIEW

**Comment by kschmanski** [comment]
@afrimzenuni I think we were looking for something like:

- User navigates to the search page
- User searches the movie they want from the search page and presumably gets multiple results
- Clicking on the link to the movie in the search results, brings them to a different page with the movie details

Is it possible to do something like this? I wouldn't think it would be too big of a coding difference. Otherwise, I would think this would leave our search page not as useful.

Also, just so that you have the most up to date code, I think you should merge master into your branch (or create a new branch, off of the newest version of master, that might be easier) but if you want to merge the branches, able to do it relatively easily: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by afrimzenuni** [comment]
Yes but for that we need to figure out how to send string from search page to this. Did you manage to figure it out with interactionService?

**Comment by kschmanski** [comment]
@afrimzenuni it works now, check out the newest version of master. the home component sends the message to the movie-search component, and each one gets console logged. You should be able to do the same thing but going from movie search to movie detail.

**Comment by kschmanski** [comment]
Since you've done all this work already I would suggest going the route of creating a new branch, that way if you need to reference this work you can keep it around.

**Comment by afrimzenuni** [comment]
im getting this error from master
"ERROR in src/app/home/home.component.ts(50,79): error TS2339: Property 'value' does not exist on type 'HTMLElement'.
    src/app/home/home.component.ts(51,82): error TS2339: Property 'value' does not exist on type 'HTMLElement'."

**Comment by kschmanski** [comment]
@afrimzenuni it should re-compile if you compile it again. I'm not sure why but I only got that error intermittently.

**Comment by kschmanski** [comment]
@afrimzenuni sorry that's a bug, Ill create a PR right now to fix

**Comment by kschmanski** [comment]
PR to fix is here, please merge this and then it should work :) https://github.com/kschmanski/CSC436-Project/pull/26

**Comment by kschmanski** [comment]
@afrimzenuni since I figured out how to make the movie detail work, I am closing this PR. I opened up a new one [here](https://github.com/kschmanski/CSC436-Project/pull/27) this will have all of your code changes plus mine.

**Pull request closed without merging**
